baseURL = 'http://www.ronneylira.com/'
languageCode = 'en-us'
title = 'Ronney Lira Down the Code'
theme = "m10c"
staticDir = ['static']

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[params]
  author = "Ronney Lira"
  description = "Brazilian software developer based in the Netherlands."
  menu_item_separator = " - "
  avatar = "avatar.png"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/ronneylira"
  [[params.social]]
    icon = "linkedin"
    name = "Linkedin"
    url = "https://nl.linkedin.com/in/ronneylira"

  # Default theme
  [params.style]
    darkestColor = "#28475C"
    darkColor = "#3D596C"
    lightColor = "#EAE7E7"
    lightestColor = "#F9F8EB"
    primaryColor = "#2F8886"